version: '3'

services:
    app:
        depends_on:
            - db
        build:
            context: ./packages
            args:
                - NODE_VERSION=${NODE_VERSION}
                - DATABASE_HOST=${MYSQL_HOST}
                - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
        deploy:
            restart_policy:
                condition: on-failure
        working_dir: /usr/src/app
        networks:
            - localnetwork
    db:
        build:
            context: .
            dockerfile: Dockerfile.mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3376:3306
        networks:
            - localnetwork
        volumes:
            - C:/data/docker/mysql/react-with-iam:/var/lib/mysql

networks:
    localnetwork:

volumes:
    local-db-vol:
        external: true
