version: '3'

services:
    app:
        build:
            dockerfile: Dockerfile
            args:
                - NODE_ENV=production
                - PORT=3000
        image: julianmedwards/react-iam-passport:prod
        ports:
            - 3000:3000
    db:
        image: julianmedwards/react-iam-passport-db:prod
