version: '3'

services:
    app:
        build:
            dockerfile: Dockerfile.dev
            args:
                - NODE_ENV=development
                - PORT=3001
        image: julianmedwards/react-iam-passport:dev
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        ports:
            - 3001:3001
        volumes:
            - ./packages:/usr/src/app
            - /usr/src/app/node_modules/
    db:
        image: julianmedwards/react-iam-passport-db:dev
