version: '3'

services:
    db:
        build: 
            args: 
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        image: mysql:${MYSQL_VERSION}
        ports:
            - 3376:3306
        networks:
            - localnetwork
        volumes:
            - ${LOCAL_DB_PATH}:/var/lib/mysql

networks:
    localnetwork:
