version: '3'

services:
  api:
    container_name: api
    platform: linux/arm64/v8
    image: unset
    depends_on:
      - db
    environment:
      NODE_ENV: 'production'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      API_PORT: '${API_PORT}'
      RAWG_URL: '${RAWG_URL}'
      RAWG_API_TOKEN: '${RAWG_API_TOKEN}'
    restart: always
    working_dir: /usr/src/api
    ports:
      - 80:${API_PORT}
    networks:
      - localnetwork
  db:
    platform: linux/arm64/v8
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - 3306
    volumes:
      - /dev/sdh/mysql:/var/lib/mysql
    networks:
      - localnetwork

networks:
  localnetwork:
