version: '3'

services:
    api:
        depends_on:
            - db
        environment:
            NODE_ENV: 'production'
            DATABASE_HOST: 'db'
            DATABASE_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            API_PORT: '${API_PORT}'
            RAWG_URL: '${RAWG_URL}'
            RAWG_API_TOKEN: '${RAWG_API_TOKEN}'
        restart: always
        working_dir: /usr/src/api
        image: 173624809884.dkr.ecr.us-east-2.amazonaws.com/games-not-played-api
        platform: linux/arm64/v8
        container_name: api
        ports:
            - 80:${API_PORT}
        networks:
            - localnetwork
    db:
        image: mysql:${MYSQL_VERSION}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - localnetwork

networks:
    localnetwork:
