version: '3'

services:
    api:
        depends_on:
            - db
        environment:
            NODE_VERSION: '${NODE_VERSION}'
            NODE_ENV: 'production'
            DATABASE_HOST: '${MYSQL_HOST}'
            DATABASE_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            API_PORT: '${API_PORT}'
            RAWG_URL: '${RAWG_URL}'
            RAWG_API_TOKEN: '${RAWG_API_TOKEN}'
        restart: always
        working_dir: /usr/src/api
        image: 173624809884.dkr.ecr.us-east-2.amazonaws.com/games-not-played-api
        container_name: api
        ports:
            - 80:5000
        networks:
            - localnetwork
    db:
        image: mysql:${MYSQL_VERSION}
        environment:
            MYSQL_VERSION: '8-debian'
            MYSQL_ROOT_PASSWORD: 'password'
        restart: always
        ports:
            - 3376:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - localnetwork

networks:
    localnetwork:
