version: '3'

services:
  api:
    container_name: api
    image: populateinbuild
    platform: linux/arm64/v8
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: 'production'
      DATABASE_HOST: 'db'
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_USER_PASSWORD}
      API_PORT: ${API_PORT}
      RAWG_URL: ${RAWG_URL}
      CLIENT_DOMAIN: ${CLIENT_DOMAIN}
    restart: always
    working_dir: /usr/src/api
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - localnetwork
  db:
    container_name: db
    image: ${MYSQL_IMAGE}
    platform: linux/arm64/v8
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data:/var/lib/mysql
    networks:
      - localnetwork

networks:
  localnetwork:
