name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build the client and server
    uses: julianmedwards/final-project-games-not-played/.github/workflows/build.yml@main
  deploy-client:
    name: Deploy client
    needs: build
    uses: julianmedwards/final-project-games-not-played/.github/workflows/build.yml@main
  # deploy-server:
  # name: Deploy server
  # needs: build
  # uses: julianmedwards/final-project-games-not-played/.github/workflows/deploy-server.yml@main
  # secrets: inherit
