name: Deploy server to AWS

on:
  # Can only be called by other workflows
  workflow_call:
    inputs:
      version-tag:
        description: 'Deployment version as time string generated in build.'
        required: true
        type: string

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Download api app package to upload to ELB
      # api-package.zip extracts to games-not-played-api.zip
      - name: Download ELB package artifact
        uses: actions/download-artifact@v3
        with:
          name: api-package

      - name: Download migrations artifact
        uses: actions/download-artifact@v3
        with:
          name: migrations

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        id: get-aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          unset-current-credentials: true
          role-to-assume: arn:aws:iam::173624809884:role/GithubActionsAutomator
          aws-region: us-east-2
          output-credentials: true

      # Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: '173624809884'
          mask-password: 'true'

      # Install Node for running Sequelize migrations
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sequelize and sequelize-cli
        run: npm install sequelize sequelize-cli mysql2

      # Run Sequelize migrations
      - name: Extract migrations package
        run: unzip migrations.zip -d .

      - name: Run Sequelize migrations
        env:
          DATABASE_USER_PASSWORD: ${{ secrets.DATABASE_USER_PASSWORD }}
          DATABASE_HOST: ${{ vars.DATABASE_HOST }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
        run: |
          npx sequelize db:migrate --migrations-path ./migrations --config ./dbConfig.js --env production

      # Deploy server to ELB application
      - name: Deploy server to ELB application
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ steps.get-aws-creds.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.get-aws-creds.outputs.aws-secret-access-key }}
          application_name: games-not-played
          environment_name: games-not-played-production
          version_label: games-not-played-${{ inputs.version-tag }}
          region: us-east-2
          deployment_package: games-not-played-api.zip
