name: Deploy server to AWS

on:
  # Can be manually run or called by other workflows
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    environment: production

    permissions:
      contents: write
      id-token: write

    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # role-to-assume:
          aws-region: us-east-2

      # Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: '173624809884.dkr.ecr.us-east-2.amazonaws.com'
          mask_password: 'true'

      # Deploy server to Elastic Beanstalk application
      - name: Deploy server to Elastic Beanstalk application
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          application_name: games-not-played-api
          # environment_name:
          # version_label:
          region: us-east-1
