name: Deploy server to AWS

on:
  # Can be manually run or called by other workflows
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download EBS package artifact
        uses: actions/download-artifact@v3
        with:
          name: api-package

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        id: get-aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::173624809884:role/GithubActionsAutomator
          aws-region: us-east-2
          output-credentials: true

      # Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: '173624809884'
          mask-password: 'true'

      # Deploy server to Elastic Beanstalk application
      - name: Deploy server to Elastic Beanstalk application
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ steps.get-aws-creds.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.get-aws-creds.outputs.aws-secret-access-key }}
          application_name: games-not-played
          environment_name: games-not-played-production
          version_label: games-not-played-${{ needs.build.outputs.version-tag }}
          region: us-east-1
          deployment_package: games-not-played-api.zip
